infostander_admin_homepage:
    pattern:  /
    defaults: { _controller: InfostanderAdminBundle:Booking:index }

infostander_admin_user:
  pattern: /user
  defaults: { _controller: InfostanderAdminBundle:User:index }

infostander_admin_screen:
    pattern:  /screen
    defaults: { _controller: InfostanderAdminBundle:Screen:index }

infostander_admin_screen_add:
    pattern: /screen/add
    defaults: { _controller: InfostanderAdminBundle:Screen:add }

infostander_admin_screen_delete:
    path:      /screen/delete/{id}
    defaults:  { _controller: InfostanderAdminBundle:Screen:delete }

infostander_admin_screen_new_activation_code:
    path:      /screen/new_activation_code/{id}
    defaults:  { _controller: InfostanderAdminBundle:Screen:newActivationCode }

infostander_admin_slide:
   pattern: /slide
   defaults: { _controller: InfostanderAdminBundle:Slide:index }

infostander_admin_slide_toggle_showarchived:
  pattern: /slide/togglearchived
  defaults: { _controller: InfostanderAdminBundle:Slide:toggleShowArchived }

infostander_admin_slide_add:
    pattern: /slide/add
    defaults: { _controller: InfostanderAdminBundle:Slide:add }

infostander_admin_slide_delete:
    path:      /slide/delete/{id}
    defaults:  { _controller: InfostanderAdminBundle:Slide:delete }

infostander_admin_slide_archived:
    path:      /slide/archived/{id}
    defaults:  { _controller: InfostanderAdminBundle:Slide:toggleArchived }

infostander_admin_booking_change_sort_order:
    path: /booking/sortorder/{id}/{updown}
    defaults:  { _controller: InfostanderAdminBundle:Booking:changeSortOrder }

infostander_admin_booking:
    path:      /booking
    defaults:  { _controller: InfostanderAdminBundle:Booking:index }

infostander_admin_booking_add:
    path:      /booking/add
    defaults:  { _controller: InfostanderAdminBundle:Booking:add }

infostander_admin_booking_edit:
    path:      /booking/edit/{id}
    defaults:  { _controller: InfostanderAdminBundle:Booking:edit }

infostander_admin_api_screen_activate:
  path:       /api/screen/activate
  defaults:   { _controller: InfostanderAdminBundle:Api:screenActivate }

infostander_admin_api_screen_get:
  path:       /api/screen/get
  defaults:   { _controller: InfostanderAdminBundle:Api:screenGet }