infostander_admin_homepage:
    pattern:  /
    defaults: { _controller: InfostanderAdminBundle:Default:index }

infostander_admin_screen:
    pattern:  /screen
    defaults: { _controller: InfostanderAdminBundle:Screen:index }
