infostander_admin_homepage:
    pattern:  /
    defaults: { _controller: InfostanderAdminBundle:Default:index }

infostander_admin_screen:
    pattern:  /screen
    defaults: { _controller: InfostanderAdminBundle:Screen:index }

infostander_admin_screen_add:
    pattern: /screen/add
    defaults: { _controller: InfostanderAdminBundle:Screen:add }

infostander_admin_screen_delete:
    path:      /screen/delete/{id}
    defaults:  { _controller: InfostanderAdminBundle:Screen:delete }

infostander_admin_screen_new_activation_code:
    path:      /screen/new_activation_code/{id}
    defaults:  { _controller: InfostanderAdminBundle:Screen:newActivationCode }

infostander_admin_slide:
    pattern: /slide
    defaults: { _controller: InfostanderAdminBundle:Slide:index }

infostander_admin_slide_add:
    pattern: /slide/add
    defaults: { _controller: InfostanderAdminBundle:Slide:add }

infostander_admin_slide_delete:
    path:      /slide/delete/{id}
    defaults:  { _controller: InfostanderAdminBundle:Slide:delete }

infostander_admin_slide_archived:
    path:      /slide/archived/{id}
    defaults:  { _controller: InfostanderAdminBundle:Slide:toggleArchived }

infostander_admin_booking:
    path:      /booking
    defaults:  { _controller: InfostanderAdminBundle:Booking:index }

infostander_admin_booking_add:
    path:      /booking/add
    defaults:  { _controller: InfostanderAdminBundle:Booking:add }

