infostander_admin_homepage:
    pattern:  /
    defaults: { _controller: InfostanderAdminBundle:Default:index }

infostander_admin_screen:
    pattern:  /screen
    defaults: { _controller: InfostanderAdminBundle:Screen:index }

infostander_admin_screen_add:
    pattern: /screen/add
    defaults: { _controller: InfostanderAdminBundle:Screen:add }

infostander_admin_screen_delete:
    path:      /screen/delete/{id}
    defaults:  { _controller: InfostanderAdminBundle:Screen:delete }

infostander_admin_screen_newtoken:
    path:      /screen/newtoken/{id}
    defaults:  { _controller: InfostanderAdminBundle:Screen:newToken }