parameters:

services:
    infostander.form.type.screen:
        class: Infostander\AdminBundle\Form\Type\ScreenType
        tags:
            - { name: form.type, alias: screen }
    infostander.form.type.slide:
        class: Infostander\AdminBundle\Form\Type\SlideType
        tags:
            - { name: form.type, alias: slide }
    infostander.form.type.booking:
        class: Infostander\AdminBundle\Form\Type\BookingType
        tags:
            - { name: form.type, alias: booking }