parameters:

services:
    infostander_user.registration.form.type:
        class: Infostander\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: infostander_user_registration }
    infostander_user.change_password.form.type:
        class: Infostander\UserBundle\Form\Type\ChangePasswordFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: infostander_user_change_password }
    infostander_user.profile.form.type:
        class: Infostander\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: infostander_user_profile }