parameters:
#    infostander_user.example.class: Infostander\UserBundle\Example

services:
#    infostander_user.example:
#        class: %infostander_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
